// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a36d13bf-4ee5-41df-be11-4969a7e3a7c2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZOZlAJR5e",
    "aws_user_pools_web_client_id": "787ucnde0n1jeuc7ud1qb5so5b",
    "aws_appsync_graphqlEndpoint": "https://mwx2wrl6jfanfgf4luvmc5sfoa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
